# This is a docker compose template file for running docker's containers locally.
# It must be combined with `compose.es.yaml`
# See: docker-start unit in Makefile

services:
    php:
        container_name: php
        build:
            dockerfile: php/Dockerfile
        volumes:
            - ../:/var/www/html
        networks:
            - elastic
        environment:
            - ES_HOST=es01
            - PROXY_HOST=proxy
            - ES_VERSION=${ES_VERSION}
        stdin_open: true
        tty: true

networks:
    elastic:
        driver: bridge
